const marketModel = {
    location: '군자동',
    items: [
        {
            id: 1,
            title: '에어팟 프로',
            location: '군자동',
            timeText: '3일 전',
            price: '220,000원',
            img: '/imgs/airpods-pro.png',
            chats: 3,
            likes: 11,
            isSold: true,
        },
        {
            id: 2,
            title: '바이레도 블랑쉬 50ml',
            location: '광진구 구의제3동',
            timeText: '26초 전',
            price: '4,000원',
            img: '/imgs/byredo-blanche.png',
            chats: 0,
            likes: 2,
            isSold: false,
        },
        {
            id: 3,
            title: '샌드위치',
            location: '동대문구 휘경동',
            timeText: '끌올 59초 전',
            price: '8,000원',
            img: '/imgs/sandwich.png',
            chats: 0,
            likes: 0,
            isSold: true,
        },
        {
            id: 4,
            title: '아이폰 13프로맥스',
            location: '군자동',
            timeText: '1일 전',
            price: '1,000,000원',
            img: '/imgs/iphone-13-pro-max.png',
            chats: 0,
            likes: 0,
            isSold: false,
        },
        {
            id: 5,
            title: '커피머신',
            location: '구리시 교문1동',
            timeText: '1초 전',
            price: '100,000원',
            img: '/imgs/coffee-machine.png',
            chats: 0,
            likes: 0,
            isSold: false,
        },
    ],
};

export default marketModel;
